" sensible defaults
set expandtab
set smarttab
set tabstop=4
set shiftwidth=4

set autoindent
set nosmartindent
set cindent

set number

set splitright
set splitbelow

set incsearch
set nohlsearch
set ignorecase
set smartcase

" for development
let &runtimepath .= ',' . getcwd()
let $NVIM_RPLUGIN_MANIFEST = './script/rplugin.vim'

" keybindings
nnoremap <Leader>x :MySQLExecQueryUnderCursor<CR>
nnoremap R :MySQLShowResults<CR>
nnoremap K :MySQLKillQuery<CR>
nnoremap <Leader>c :MySQLCountTableUnderCursor<CR>
nnoremap <Leader>d :MySQLDescribeTableUnderCursor<CR>
nnoremap <Leader>i :MySQLShowIndexesFromTableUnderCursor<CR>
nnoremap <Leader>s :MySQLSampleTableUnderCursor<CR>

" nvim-mysql options

" aliases: map from alias -> connection string
let g:nvim_mysql#aliases = {}

" auto_close_results: close results window automatically if it's the last
" window in a tab
let g:nvim_mysql#auto_close_results = 1
