" sensible defaults
set expandtab
set smarttab
set tabstop=4
set shiftwidth=4

set autoindent
set nosmartindent
set cindent

set number

set splitright
set splitbelow

set incsearch
set nohlsearch
set ignorecase
set smartcase

" for development
let &runtimepath .= ',' . getcwd()
let $NVIM_RPLUGIN_MANIFEST = './script/rplugin.vim'

" keybindings
nnoremap <CR> :MySQLExecQueryUnderCursor<CR>
nnoremap R :MySQLShowResults<CR>
nnoremap K :MySQLKillQuery<CR>
nnoremap <Leader>d :MySQLDescribeTableUnderCursor<CR>
nnoremap <Leader>s :MySQLSampleTableUnderCursor<CR>
