" sensible defaults
set expandtab
set smarttab
set tabstop=4
set shiftwidth=4

set autoindent
set nosmartindent
set cindent

set number

set splitright
set splitbelow

set incsearch
set nohlsearch
set ignorecase
set smartcase

" for development
let &runtimepath .= ',' . getcwd()
let $NVIM_RPLUGIN_MANIFEST = './script/rplugin.vim'

" nvim-mysql options

" keymaps: override default keymaps. map from command -> key(s). see KEYMAPS
" dict in __init__.py for possible commands.
let g:nvim_mysql#keymaps = {}

" aliases: map from alias -> connection string
let g:nvim_mysql#aliases = {}

" auto_close_results: close results window automatically if it's the last
" window in a tab
let g:nvim_mysql#auto_close_results = 1

" aux_window_pref: which aux window (results or tree) should take up full
" space?
let g:nvim_mysql#aux_window_pref = 'results'

" use_spinner: when a query is running, display an animated spinner
let g:nvim_mysql#use_spinner = 1
